In [36]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

In [332]:
import numpy as np
import scipy.linalg

In [333]:
# ndim
a = np.array([[0, 1, 2, 3, 4, 5]])
np.ndim(a)

2

In [334]:
# size
a.size

6

In [335]:
# shape
np.shape(a)
a.shape

a.shape[0]
a.shape[1]

(1, 6)

(1, 6)

1

6

In [336]:
# preparation
b = np.array([11, 22])
c = np.array([[1.,2.,3.], [4.,5.,6.]])
d = np.array([[5, 5, 5, 5, 5], [5, 5, 5, 5, 5]])

In [337]:
# Run block command
e = np.block([[a, b], [c, d]])
e.ndim
e.size
e.shape
print(e)

2

24

(3, 8)

[[ 0.  1.  2.  3.  4.  5. 11. 22.]
 [ 1.  2.  3.  5.  5.  5.  5.  5.]
 [ 4.  5.  6.  5.  5.  5.  5.  5.]]


In [101]:
a[-1]
c[-1]
c[-1][-1]
c[0, 2] # first row, third col

array([0, 1, 2, 3, 4, 5])

array([4., 5., 6.])

6.0

3.0

In [170]:
f = np.array([[1, 2, 3, 4, 5, 6, 7],
             [8, 9, 10, 11, 12, 13, 14],
             [15, 16, 17, 18, 19, 20, 21],
             [22, 23, 24, 25, 26, 27, 28]])
f[:3]
f[0:2, :]
f[:3][:, 5:7] # read only access

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

array([[ 6,  7],
       [13, 14],
       [20, 21]])

In [143]:
f[np.ix_([0, 3], [2, 6])]

array([[ 3,  7],
       [24, 28]])

In [144]:
f[ 0:3:2, :]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [15, 16, 17, 18, 19, 20, 21]])

In [145]:
f[:, ::2] # equivalent to f[:, 0:7:2]

array([[ 1,  3,  5,  7],
       [ 8, 10, 12, 14],
       [15, 17, 19, 21],
       [22, 24, 26, 28]])

In [146]:
f[::-1, :]

array([[22, 23, 24, 25, 26, 27, 28],
       [15, 16, 17, 18, 19, 20, 21],
       [ 8,  9, 10, 11, 12, 13, 14],
       [ 1,  2,  3,  4,  5,  6,  7]])

In [147]:
f[np.r_[:len(f), 0]]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [ 1,  2,  3,  4,  5,  6,  7]])

In [148]:
f[np.r_[:len(f), 2]]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [15, 16, 17, 18, 19, 20, 21]])

In [149]:
f.T

array([[ 1,  8, 15, 22],
       [ 2,  9, 16, 23],
       [ 3, 10, 17, 24],
       [ 4, 11, 18, 25],
       [ 5, 12, 19, 26],
       [ 6, 13, 20, 27],
       [ 7, 14, 21, 28]])

In [150]:
g = np.array([[ 1.-1.j,  0.-2.j],
              [ 0.-0.j,  1.-1.j]])
g.conj()
g.conj().transpose()

array([[1.+1.j, 0.+2.j],
       [0.-0.j, 1.+1.j]])

array([[1.+1.j, 0.-0.j],
       [0.+2.j, 1.+1.j]])

In [151]:
m1 = np.array([[1, 2, 3], [4, 5, 6]])
m2 = np.array([[1, 2], [3, 4], [5, 6]])
m1 @ m2
m1 * m1

array([[22, 28],
       [49, 64]])

array([[ 1,  4,  9],
       [16, 25, 36]])

In [152]:
m1 / m1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [153]:
m1 ** 3

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [154]:
f > 10

array([[False, False, False, False, False, False, False],
       [False, False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [155]:
np.nonzero(f > 10)

(array([1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3]),
 array([3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6]))

In [190]:
v = np.array([0, 1, 2, 3, 4, 5])
f[:,np.nonzero(v > 2)[0]]

array([[ 4,  5,  6],
       [11, 12, 13],
       [18, 19, 20],
       [25, 26, 27]])

In [201]:
v = np.array([[0], [1], [2], [3], [4], [5], [6]])
f[:,v.T[0] > 2]

array([[ 4,  5,  6,  7],
       [11, 12, 13, 14],
       [18, 19, 20, 21],
       [25, 26, 27, 28]])

In [175]:
h = f.copy()
h[h < 10] = 0
h

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28]])

In [179]:
h = f.copy()
h * (h > 10)

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28]])

In [180]:
h[:] = 3
h

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [183]:
flat = f.flatten() # this forces a copy
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [187]:
np.arange(1.,11.)
np.r_[1.:11.]
np.r_[1:10:10j]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [202]:
np.arange(10.)
np.r_[:10.]
np.r_[:9:10j]

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [205]:
np.arange(1.,11.)[:, np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [208]:
np.zeros((3,4))
np.ones((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [207]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [209]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [213]:
s = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.diag(s)
np.diag(f)

array([1, 5, 9])

array([ 1,  9, 17, 25])

In [218]:
np.diag(b, 0)

array([[11,  0],
       [ 0, 22]])

In [220]:
np.random.rand(3, 4)

array([[0.64565677, 0.70384053, 0.14604837, 0.29555082],
       [0.56843945, 0.24421295, 0.4664716 , 0.85634273],
       [0.81860282, 0.35680616, 0.82767747, 0.22105152]])

In [221]:
np.linspace(1, 3, 4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [224]:
np.mgrid[0:9., 0:6.]
np.meshgrid(np.r_[0:9.], np.r_[0:6.])

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.]],

       [[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]]])

[array([[0., 1., 2., 3., 4., 5., 6., 7., 8.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8.]]),
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.]])]

In [226]:
np.ogrid[0:9., 0:6.]
np.ix_(np.r_[0:9.], np.r_[0:6.])

[array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]), array([[0., 1., 2., 3., 4., 5.]])]

(array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]), array([[0., 1., 2., 3., 4., 5.]]))

In [228]:
np.meshgrid([1, 2, 4], [2, 4, 5])

[array([[1, 2, 4],
        [1, 2, 4],
        [1, 2, 4]]), array([[2, 2, 2],
        [4, 4, 4],
        [5, 5, 5]])]

In [229]:
np.ix_([1,2,4],[2,4,5])

(array([[1],
        [2],
        [4]]), array([[2, 4, 5]]))

In [231]:
np.tile(s, (2, 2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [237]:
np.concatenate((np.zeros((3, 3)), np.ones((3, 4))),1)
np.hstack((np.zeros((3, 3)), np.ones((3, 4))))
np.column_stack((np.zeros((3, 3)), np.ones((3, 4))))
np.c_[(np.zeros((3, 3)), np.ones((3, 4)))]

array([[0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.]])

array([[0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.]])

array([[0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.]])

array([[0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.]])

In [238]:
np.concatenate((np.zeros((2, 3)), np.ones((3, 3))))
np.vstack((np.zeros((2, 3)), np.ones((3, 3))))
np.r_[np.zeros((2, 3)), np.ones((3, 3))]

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [240]:
f.max()
f.max(0)
f.max(1)

28

array([22, 23, 24, 25, 26, 27, 28])

array([ 7, 14, 21, 28])

In [244]:
np.maximum(f, h)

array([[ 3,  3,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28]])

In [248]:
v = np.array([0, 1, 2, 3, 4, 5])
np.sqrt(v @ v)
np.linalg.norm(v)

7.416198487095663

7.416198487095663

In [251]:
np.logical_and(f > 10, f > 20)
np.logical_or(f > 10, f > 20)

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

array([[False, False, False, False, False, False, False],
       [False, False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [258]:
x = 20 # 10100
y = 11 # 1011
x & y
x | y

0

31

In [260]:
np.linalg.inv(s)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [261]:
np.linalg.pinv(s)

array([[-6.38888889e-01, -1.66666667e-01,  3.05555556e-01],
       [-5.55555556e-02,  1.38777878e-16,  5.55555556e-02],
       [ 5.27777778e-01,  1.66666667e-01, -1.94444444e-01]])

In [262]:
np.linalg.matrix_rank(s)

2

In [271]:
np.linalg.solve(s, np.ones((3, 1))) # if a is square
np.linalg.lstsq(f, np.ones((4, 1)))

array([[ 0.2],
       [-1.4],
       [ 1.2]])

/Users/kusmour/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


(array([[-1.07142857e-01],
        [-7.14285714e-02],
        [-3.57142857e-02],
        [-1.22264956e-17],
        [ 3.57142857e-02],
        [ 7.14285714e-02],
        [ 1.07142857e-01]]),
 array([], dtype=float64),
 2,
 array([8.76870510e+01, 4.99810768e+00, 2.83533862e-15, 1.63366387e-15]))

In [274]:
U, S, Vh = np.linalg.svd(f)
V = Vh.T
U
S
V

array([[-0.12643366, -0.82705171,  0.5451995 ,  0.05251198],
       [-0.33643978, -0.43221323, -0.76607278,  0.33635173],
       [-0.54644591, -0.03737474, -0.10345292, -0.83023942],
       [-0.75645203,  0.35746374,  0.32432621,  0.4413757 ]])

array([8.76870510e+01, 4.99810768e+00, 2.83533862e-15, 1.63366387e-15])

array([[-0.31540102,  0.6039933 ,  0.72492677, -0.08276889,  0.02812439,
        -0.05046243, -0.00270764],
       [-0.33553821,  0.416087  , -0.56672688, -0.59702407,  0.16012881,
        -0.00115744,  0.10500495],
       [-0.35567541,  0.2281807 , -0.30091164,  0.43994391, -0.51157531,
        -0.35456016, -0.38717943],
       [-0.37581261,  0.04027439, -0.10791191,  0.4220043 , -0.11995968,
         0.48710377,  0.64478667],
       [-0.3959498 , -0.14763191, -0.05222407,  0.35000789,  0.79641341,
        -0.16260496, -0.188364  ],
       [-0.416087  , -0.33553821,  0.11590417, -0.24407067, -0.15603694,
         0.59070101, -0.51769318],
       [-0.4362242 , -0.52344452,  0.18694355, -0.28809248, -0.19709469,
        -0.5090198 ,  0.34615264]])

In [278]:
np.linalg.cholesky(np.array([[1,-2j],[2j,5]])).T

array([[1.+0.j, 0.+2.j],
       [0.+0.j, 1.+0.j]])

In [282]:
D,V = np.linalg.eig(s)
D
V

array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16])

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

In [287]:
Q, R = scipy.linalg.qr(s)

In [296]:
P, L, U = scipy.linalg.lu(np.array([[4, 3], [6, 3]]))
P
L
U

array([[0., 1.],
       [1., 0.]])

array([[1.        , 0.        ],
       [0.66666667, 1.        ]])

array([[6., 3.],
       [0., 1.]])

In [302]:
scipy.fft(a)
scipy.ifft(a)

array([[15.+0.j        , -3.+5.19615242j, -3.+1.73205081j,
        -3.+0.j        , -3.-1.73205081j, -3.-5.19615242j]])

array([[ 2.5+0.j        , -0.5-0.8660254j , -0.5-0.28867513j,
        -0.5+0.j        , -0.5+0.28867513j, -0.5+0.8660254j ]])

In [305]:
np.sort(f.T)

array([[ 1,  8, 15, 22],
       [ 2,  9, 16, 23],
       [ 3, 10, 17, 24],
       [ 4, 11, 18, 25],
       [ 5, 12, 19, 26],
       [ 6, 13, 20, 27],
       [ 7, 14, 21, 28]])

In [320]:
st = np.array([[2, 2, 3], [3, 3, 2]])
I = np.argsort(st[:, 2])
st[I,:]

array([[3, 3, 2],
       [2, 2, 3]])

In [328]:
x = np.array([0, 1, 2, 3])
A = np.vstack([x, np.ones(len(x))]).T
y = np.array([-1, 0.2, 0.9, 2.1])
np.linalg.lstsq(A, y)

/Users/kusmour/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  after removing the cwd from sys.path.


(array([ 1.  , -0.95]), array([0.05]), 2, array([4.10003045, 1.09075677]))

In [339]:
np.unique(h)

array([3])

In [344]:
ss = np.array([[[0], [1], [2]]])
ss.squeeze()
v.squeeze()

array([0, 1, 2])

array([0, 1, 2, 3, 4, 5])